### ISSUE TITLE
Fix Requirements.txt

### ISSUE THREAD

**Issue by Jeffrey-Lim** [schobbejak/winning_solution#12]
When I try `pip install -r requirements.txt` it fails to install `torch==2.0.2+cu11`.

**Comment by tolgakopar** [comment]
try this $ pip install -r requirements.txt --find-links https://download.pytorch.org/whl/cu118

**Comment by tolgakopar** [comment]
what about using this in requirements instead of the torch stuff

--extra-index-url https://download.pytorch.org/whl/cu118
torch
torchvision
torchaudio
